[config]
default_to_workspace = false
min_version = "0.32.15"

[config.modify_core_tasks]
private = true
namespace = "default"

[tasks.mzoon]
description = "Run MZoon"
command = "cargo"
args = ["run", "--target", "x86_64-unknown-linux-gnu", "--manifest-path", "../../crates/mzoon/Cargo.toml", "${@}"]


